name: "InstantCommand"
version: "1.1"
main: "vb.$instantcommand.PluginMain"
api-version: 1.13
author: "Martinez"
description: "Plugin allows your players to perform configured command really fast!"
commands:
  instantcommandreload:
    aliases: [icr]
    description: "Reload"
    permission: "instantcommand.reload"
    permission-message: "No permissions"
permissions:
  instantcommand.reload:
    default: op
